version: "3.9"

services:
    app:
        build: .
        image: cryopaste_app
        container_name: cryopaste.com
        restart: always
        networks:
            - web
        volumes:
            - '/var/log:/var/log'
        labels:
            - traefik.enable=true
            - traefik.http.routers.cryopaste.entrypoints=web
            - traefik.http.routers.cryopaste.rule=Host("cryopaste.com")

networks:
    web:
        external: true
